config = {'version': 'v1', 'config': {'visState': {'filters': [{'dataId': ['algae'], 'id': 'awrx7g97e', 'name': ['fecha'], 'type': 'timeRange', 'value': [-2195942400000, 1546300800000], 'enlarged': False, 'plotType': 'histogram', 'animationWindow': 'free', 'yAxis': None, 'speed': 1}], 'layers': [{'id': '1oqpmx', 'type': 'cluster', 'config': {'dataId': 'algae', 'label': 'Point', 'color': [77, 193, 156], 'highlightColor': [252, 242, 26, 255], 'columns': {'lat': 'lat', 'lng': 'lon'}, 'isVisible': True, 'visConfig': {'opacity': 0.8, 'clusterRadius': 40, 'colorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'radiusRange': [0, 50], 'colorAggregation': 'average'}, 'hidden': False, 'textLabel': [{'field': None, 'color': [255, 255, 255], 'size': 18, 'offset': [0, 0], 'anchor': 'start', 'alignment': 'center'}]}, 'visualChannels': {'colorField': {'name': 'number_ind', 'type': 'integer'}, 'colorScale': 'quantile'}}], 'interactionConfig': {'tooltip': {'fieldsToShow': {'algae': [{'name': 'fecha', 'format': None}, {'name': 'species', 'format': None}, {'name': 'number_ind', 'format': None}]}, 'compareMode': False, 'compareType': 'absolute', 'enabled': True}, 'brush': {'size': 0.5, 'enabled': False}, 'geocoder': {'enabled': False}, 'coordinate': {'enabled': False}}, 'layerBlending': 'normal', 'splitMaps': [], 'animationConfig': {'currentTime': None, 'speed': 1}}, 'mapState': {'bearing': 24, 'dragRotate': True, 'latitude': 44.74252780520073, 'longitude': -7.931230108946205, 'pitch': 50, 'zoom': 3.773067696032695, 'isSplit': False}, 'mapStyle': {'styleType': 'dark', 'topLayerGroups': {}, 'visibleLayerGroups': {'label': True, 'road': True, 'border': False, 'building': True, 'water': True, 'land': True, '3d building': False}, 'threeDBuildingColor': [9.665468314072013, 17.18305478057247, 31.1442867897876], 'mapStyles': {}}}}


config2 = {'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [{'id': 'rxwekcj', 'type': 'hexagon', 'config': {'dataId': 'crimes', 'label': 'crimes', 'color': [221, 178, 124], 'columns': {'lat': 'lat', 'lng': 'lon'}, 'isVisible': True, 'visConfig': {'opacity': 0.8, 'worldUnitSize': 0.1, 'resolution': 8, 'colorRange': {'name': 'Global Warming', 'type': 'sequential', 'category': 'Uber', 'colors': ['#5A1846', '#900C3F', '#C70039', '#E3611C', '#F1920E', '#FFC300']}, 'coverage': 1, 'sizeRange': [0, 500], 'percentile': [0, 100], 'elevationPercentile': [0, 100], 'elevationScale': 17, 'colorAggregation': 'count', 'sizeAggregation': 'count', 'enable3d': True}, 'hidden': False, 'textLabel': [{'field': None, 'color': [255, 255, 255], 'size': 18, 'offset': [0, 0], 'anchor': 'start', 'alignment': 'center'}]}, 'visualChannels': {'colorField': None, 'colorScale': 'quantile', 'sizeField': None, 'sizeScale': 'linear'}}], 'interactionConfig': {'tooltip': {'fieldsToShow': {'crimes': [{'name': 'INCIDENT_KEY', 'format': None}, {'name': 'OCCUR_DATE', 'format': None}, {'name': 'OCCUR_TIME', 'format': None}, {'name': 'BORO', 'format': None}, {'name': 'PRECINCT', 'format': None}]}, 'compareMode': False, 'compareType': 'absolute', 'enabled': True}, 'brush': {'size': 0.5, 'enabled': False}, 'geocoder': {'enabled': False}, 'coordinate': {'enabled': False}}, 'layerBlending': 'normal', 'splitMaps': [], 'animationConfig': {'currentTime': None, 'speed': 1}}, 'mapState': {'bearing': 24, 'dragRotate': True, 'latitude': 40.7370321312986, 'longitude': -73.95194934994169, 'pitch': 50, 'zoom': 10, 'isSplit': False}, 'mapStyle': {'styleType': 'dark', 'topLayerGroups': {}, 'visibleLayerGroups': {'label': True, 'road': True, 'border': False, 'building': True, 'water': True, 'land': True, '3d building': False}, 'threeDBuildingColor': [9.665468314072013, 17.18305478057247, 31.1442867897876], 'mapStyles': {}}}}



con = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['algae'],
     'id': 'awrx7g97e',
     'name': ['fecha'],
     'type': 'timeRange',
     'value': [-2195942400000, 1546300800000],
     'enlarged': False,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 1}],
   'layers': [{'id': '1oqpmx',
     'type': 'cluster',
     'config': {'dataId': 'algae',
      'label': 'Point',
      'color': [77, 193, 156],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat': 'lat', 'lng': 'lon'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'clusterRadius': 40,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radiusRange': [0, 50],
       'colorAggregation': 'average'},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'number_ind',
       'type': 'integer'},
      'colorScale': 'quantile'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'algae': [{'name': 'fecha',
        'format': None},
       {'name': 'species', 'format': None},
       {'name': 'number_ind', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 24,
   'dragRotate': True,
   'latitude': 44.74252780520073,
   'longitude': -7.931230108946205,
   'pitch': 50,
   'zoom': 3.773067696032695,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}